Several fixes / changes to the `holder` item action
apace100/apoli pull request #132
Opened 2023-07-25 07:31 UTC by apace100

This PR includes several changes regarding the holder item action:

1. Optimized the `InventoryUtil#forEachStack` method to not allocate a new set each call
2. Changed the setting of holder entities from vanilla's `setHolder` to our duck interface's `EntityLinkedItemStack#setEntity`. This is better because it does not change vanilla semantics of the holder field.
3. Added a test power.
4. Renamed `holder` to `holder_action` and the `entity_action` field to `action`. This is to make it in line with other actions, like `equipped_item_action`, `passenger_action`, etc. I feel this is okay since the action hasn't been released for too long and is probably still barely used. If you think this is too late for that change, we could add an alias using the old names for backwards compatibility and make an announcement asking people to change over to the new names quickly.

Thanks Pug for pointing out the optimization potential with the method.

2023-07-25 07:54 UTC, MerchantPug requested changes
~~I don't quite see the point in keeping `InventoryUtil#deduplicateSlots` when we aren't using it anymore and when it's private.~~

~~If it is still used, please tell me and I'll approve. I can't quite check properly on my phone.~~

I feel like we could implement these optimisations to the other methods too.

2023-07-25 07:54 UTC, MerchantPug commented on src/main/java/io/github/apace100/apoli/util/InventoryUtil.java
>      private static void deduplicateSlots(Entity entity, Set<Integer> slots) {
Are we sure that this method should be kept here? We aren't using it anymore and it also isn't exposed for anybody else to use, so I feel like we could remove it.

2023-07-25 08:06 UTC, MerchantPug commented on src/main/java/io/github/apace100/apoli/util/InventoryUtil.java
>      private static void deduplicateSlots(Entity entity, Set<Integer> slots) {
There's two things we can do here as this method **is** used.

1. Ignore this review.
2. Implement the optimisations to the set creation inside the other `InventoryUtil` methods.

2023-07-25 20:08 UTC, MerchantPug approved these changes
The above is invalid, please ignore it.

2023-07-26 08:42 UTC, eggohito approved these changes
Looks good! I agree on adding a path alias for it, though identifier aliasing is currently not perfect (it doesn't have a priority system of some sort similar to `Prioritized.CallInstance<?>`)

2023-07-27 00:35 UTC, MerchantPug commented
> Looks good! I agree on adding a path alias for it, though identifier aliasing is currently not perfect (it doesn't have a priority system of some sort similar to `Prioritized.CallInstance<?>`)

Agreed on having a  path alias.

2023-08-04 00:33 UTC, merged