Added inverted field to hud render
apace100/apoli pull request #4
Opened 2021-08-15 17:40 UTC by MerchantPug

This change allows for bars that start as filled and empty over time.
It also shouldn't break existing datapacks as inverted defaults to false.

Here's how it looks in datapacks.
```json
"hud_render": {
    "should_render": true,
    "bar_index": 0,
    "inverted": true
}
```

2021-08-15 17:45 UTC, MerchantPug commented
Feel free to change the name from inverted, I was just using it because it was a familiar term.

2021-08-16 11:51 UTC, MerchantPug commented
Idk how to specify only one commit as a PR so this'll have to do.

Feel free to pick and choose what you want in Apoli.

2021-08-16 23:56 UTC, Alluysl commented
To be coherent with resource bars, shouldn't the elytra texture path field be named `sprite_location`?

2021-08-17 02:21 UTC, MerchantPug commented
I wouldn't call it a sprite location because it's not really a sprite, it's a texture

2021-08-17 10:31 UTC, Alluysl commented
Fair

2021-09-04 13:07 UTC, MerchantPug commented
TODO - Swap getInverted() to isInverted()

2021-09-06 07:13 UTC, apace100 requested changes
I feel like instead of handling the `inverted` property in the power types, it should be handled generally where the hud renders are drawn. That way the powers don't need to know how they are rendered, and it reduces code duplication.
(Save `hudPower.getFill()` in a variable and do `fill = 1f - fill` if the `hudPower.getInverted()` in `PowerHudRenderer` line 56)

2021-09-06 07:51 UTC, merged